### ISSUE TITLE
Vue 3.0 Support

### ISSUE THREAD

**Issue by Flamenco** [Flamenco/intellivue#14]
We have added initial Vue 3.0 support.

You can now add functions, computed, and data to your setup method.  We are still working on UI issues, so this is the place to discuss what you would like to see.

## TODO
- [x] Add checkbox to use setup method 
- [x] Add message to dialog 
- [x] Implement adding function
- [x] Implement adding ref
- [x] Implement adding computed
- [x] Persist setup method checkbox
- [ ] Choose between ref and reactive
- [ ] Implement adding reactive
- [ ] Allow specifying template type
- [ ] Use separate tab for Vue 3.0
- [ ] Add implementation to a more ideal location
- [ ] Include setup declared items in analysis
- [ ] Add to setup from analysis window

**Comment by Flamenco** [comment]
# Screenshots 

<img width="432" alt="Screen Shot 2021-05-19 at 6 31 33 PM" src="https://user-images.githubusercontent.com/819940/118893761-fb138180-b8d0-11eb-81dd-e6386ef7752e.png">

<img width="605" alt="Screen Shot 2021-05-19 at 6 31 44 PM" src="https://user-images.githubusercontent.com/819940/118893773-ffd83580-b8d0-11eb-85c0-ceb1bd9ca081.png">

<img width="332" alt="Screen Shot 2021-05-19 at 6 32 06 PM" src="https://user-images.githubusercontent.com/819940/118893778-02d32600-b8d1-11eb-8494-95532ee46240.png">

**Comment by codigovision** [comment]
It would be great to also support [Global Properties](https://v3.vuejs.org/api/application-config.html#globalproperties) and [Provide/Inject at the Component API](https://v3.vuejs.org/guide/component-provide-inject.html) level in addition to the Composition API.

**Comment by dy86** [comment]
Consider compatibility with PURE `<script setup>` ?

**Comment by Flamenco** [comment]
Yes @dy86 that is on the wish list.  Once we start using Vue3 in-house it will be added.  Currently we are using Vue2 with composition api support.

Basically we would detect the setup flag and simply not add the item to any exports.  Does that seem correct?

**Comment by Flamenco** [comment]
@dy86 `<script setup>` was just added to the latest release targeted at the EAP.  We will test in house for a few days then release.

**Comment by zanderzhg** [comment]
> @dy86 `<script setup>` was just added to the latest release targeted at the EAP. We will test in house for a few days then release.
Is script setup working?

**Comment by Flamenco** [comment]
Yes. 100% working in version 1.1.11.

https://plugins.jetbrains.com/plugin/12014-intellivue/versions/stable/165979
